CREATE TABLE IF NOT EXISTS PERFILES
(
PER_ID INTEGER PRIMARY KEY,
PER_CODIGO TEXT,
PER_NOMBRE TEXT,
PER_DESCRIPCION TEXT,
PER_ESTADO INTEGER
);

CREATE TABLE IF NOT EXISTS USUARIOS
(
USU_ID INTEGER PRIMARY KEY,
USU_RUT INTEGER , 
USU_DV TEXT,
USU_NOMBRES TEXT,
USU_APELLIDO_PATERNO TEXT,
USU_APELLIDO_MATERNO TEXT,
USU_FECHA_NACIMIENTO DATETIME,
USU_NOMBRE_USUARIO TEXT,
USU_CLAVE TEXT,
USU_FECHA_REGISTRO DATE,
USU_ESTADO INTEGER,
PER_ID INTEGER,
REG_ID INTEGER,
LUGAR_ASIGNADO_ID INTEGER,
USU_CODIGO_RESET_CONTRASENA TEXT,
USU_TELEFONO TEXT,
TUS_ID INTEGER,
ETR_ID INTEGER,
FOREIGN KEY(PER_ID) REFERENCES PERFILES(PER_ID)
);

CREATE TABLE IF NOT EXISTS APLICACIONES
(APLI_ID INTEGER PRIMARY KEY,
APLI_CODIGO TEXT,
APLI_NOMBRE TEXT,
APLI_DESCRIPCION TEXT,
APLI_METODO TEXT,
APLI_CONTROLADOR TEXT,
APLI_ESTADO INTEGER,
APLI_IMG TEXT,
TAP_ID INTEGER
);

CREATE TABLE IF NOT EXISTS PERFILES_APLICACIONES
(PER_ID INTEGER,
APLI_ID INTEGER,
FOREIGN KEY (PER_ID) REFERENCES PERFILES (PER_ID),
FOREIGN KEY (APLI_ID) REFERENCES APLICACIONES (APLI_ID)
);

CREATE TABLE IF NOT EXISTS REGISTRO_INICIO_FIN_DIA
(RIN_ID INTEGER PRIMARY KEY,
RIN_ESTADO INTEGER,
RIN_FECHA_INICIO DATETIME,
RIN_FECHA_FIN DATETIME,
USU_ID INTEGER,
RIN_SYNC INTEGER,
FOREIGN KEY (USU_ID) REFERENCES USUARIOS (USU_ID)
);

CREATE TABLE IF NOT EXISTS PARAMETROS
(
    PAR_ID INTEGER PRIMARY KEY,
    PAR_CODIGO TEXT,
    PAR_VALOR TEXT

);

CREATE TABLE IF NOT EXISTS REGIONES
(
    REG_ID INTEGER PRIMARY KEY,
    REG_CODIGO TEXT,
    REG_NOMBRE TEXT
);

CREATE TABLE IF NOT EXISTS PROVINCIAS
(
    PRO_ID INTEGER PRIMARY KEY,
    PRO_NOMBRE TEXT,
    REG_ID INTEGER,
    PRO_CODIGO TEXT
);

CREATE TABLE IF NOT EXISTS COMUNAS
(
    COM_ID INTEGER PRIMARY KEY,
    COM_NOMBRE TEXT,
    PRO_ID INTEGER,
    COM_CODIGO TEXT
);
CREATE TABLE IF NOT EXISTS TIPO_LUGARES 
(
    TIL_ID INTEGER PRIMARY KEY,
    TIL_CODIGO TEXT,
    TIL_NOMBRE TEXT,
    TIL_DESCRIPCION TEXT,
    TIL_ESTADO INTEGER
);

CREATE TABLE IF NOT EXISTS LUGARES 
(
    LUG_ID INTEGER PRIMARY KEY,
    LUG_CODIGO TEXT,
    LUG_NOMBRE TEXT,
    COM_ID INTEGER,
    LUG_CALLE TEXT,
    LUG_NUMERO INTEGER,
    LUG_LATITUD TEXT,
    LUG_LONGITUD TEXT,
    LUG_DESCRIPCION TEXT,
    TIL_ID INTEGER
);

CREATE TABLE IF NOT EXISTS EMPRESAS_TRANSPORTES
(
    ETR_ID INTEGER PRIMARY KEY,
    ETR_CODIGO TEXT,
    ETR_NOMBRE TEXT,
    ETR_DESCRIPCION TEXT,
    ETR_RUT INTEGER,
    ETR_DV TEXT,
    ETR_TELEFONO TEXT
);

CREATE TABLE IF NOT EXISTS TRANSPORTES
(
    TRA_ID INTEGER PRIMARY KEY,
    TRA_PATENTE TEXT,
    TRA_NOMBRE TEXT,
    TRA_DESCRIPCION TEXT,
    ETR_ID INTEGER,
    REG_ID INTEGER,
    TIT_ID INTEGER
);


CREATE TABLE IF NOT EXISTS COORDENADAS_USUARIOS
(CUS_ID INTEGER PRIMARY KEY,
CUS_LATITUD TEXT,
CUS_LONGITUD TEXT,
CUS_FECHA_DISPOSITIVO TEXT,
USU_ID INTEGER,
CUS_SYNC INTEGER,
FOREIGN KEY (USU_ID) REFERENCES USUARIOS (USU_ID)
);