CREATE TABLE IF NOT EXISTS PERFILES
(PER_ID INTEGER PRIMARY KEY,
PER_CODIGO TEXT,
PER_NOMBRE TEXT,
PER_DESCRIPCION TEXT,
PER_ESTADO INTEGER
);

CREATE TABLE IF NOT EXISTS USUARIOS
(USU_ID INTEGER PRIMARY KEY,
USU_RUT INTEGER , 
USU_DV TEXT,
USU_NOMBRES TEXT,
USU_APELLIDO_PATERNO TEXT,
USU_APELLIDO_MATERNO TEXT,
USU_FECHA_NACIMIENTO DATETIME,
USU_NOMBRE_USUARIO TEXT,
USU_CLAVE TEXT,
USU_FECHA_REGISTRO DATE,
USU_ESTADO INTEGER,
PER_ID INTEGER,
FOREIGN KEY(PER_ID) REFERENCES PERFILES(PER_ID)
);

CREATE TABLE IF NOT EXISTS APLICACIONES
(APLI_ID INTEGER PRIMARY KEY,
APLI_CODIGO TEXT,
APLI_NOMBRE TEXT,
APLI_DESCRIPCION TEXT,
APLI_METODO TEXT,
APLI_CONTROLADOR TEXT,
APLI_ESTADO INTEGER,
APLI_IMG TEXT,
TAP_ID INTEGER
);

CREATE TABLE IF NOT EXISTS PERFILES_APLICACIONES
(PER_ID INTEGER,
APLI_ID INTEGER,
FOREIGN KEY (PER_ID) REFERENCES PERFILES (PER_ID),
FOREIGN KEY (APLI_ID) REFERENCES APLICACIONES (APLI_ID)
);

CREATE TABLE IF NOT EXISTS REGISTRO_INICIO_FIN_DIA
(RIN_ID INTEGER PRIMARY KEY,
RIN_ESTADO INTEGER,
RIN_FECHA_INICIO DATETIME,
RIN_FECHA_FIN DATETIME,
USU_ID INTEGER,
RIN_SYNC INTEGER,
FOREIGN KEY (USU_ID) REFERENCES USUARIOS (USU_ID)
);

CREATE TABLE IF NOT EXISTS PARAMETROS
(
    PAR_ID INTEGER PRIMARY KEY,
    PAR_VALOR TEXT UNIQUE 
);

CREATE TABLE IF NOT EXISTS COORDENADAS_USUARIOS
(CUS_ID INTEGER PRIMARY KEY,
CUS_LATITUD TEXT,
CUS_LONGITUD TEXT,
CUS_FECHA_DISPOSITIVO TEXT,
USU_ID INTEGER,
CUS_SYNC INTEGER,
FOREIGN KEY (USU_ID) REFERENCES USUARIOS (USU_ID)
);

INSERT OR IGNORE INTO COORDENADAS_USUARIOS(CUS_ID, CUS_LATITUD, CUS_LONGITUD, CUS_FECHA_DISPOSITIVO, USU_ID, CUS_SYNC) VALUES (1,'-33.439','-70.650','2020-02-28 09:00:00.000',4,0);
INSERT OR IGNORE INTO COORDENADAS_USUARIOS(CUS_ID, CUS_LATITUD, CUS_LONGITUD, CUS_FECHA_DISPOSITIVO, USU_ID, CUS_SYNC) VALUES (2,'-34.1234','-71.1234','2020-02-28 09:09:09.009',4,0);